version: '3.8'
services:
  mysql_db1:
    image: mysql:latest
    container_name: mysql_salones
    environment:
      MYSQL_ROOT_PASSWORD: salones-password
      MYSQL_DATABASE: salones_db
    volumes:
      - ./docker/mysql/salones_db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
